### ISSUE TITLE
textproc/sassc missing plist

### ISSUE THREAD

**Issue by ari** [saper/ports-exp#2]

**Comment by saper** [comment]
Thanks for trying my ports! Because we publish only one file here, I have decided to use `PLIST_FILES` option in the [Makefile](https://github.com/saper/ports-exp/blob/077ce17a9519a078f48ad22e272991395bb6449b/textproc/sassc/Makefile#L24) instead. Does this work for you?

**Comment by ari** [comment]
Ah, I missed that. All good!
