### ISSUE TITLE
Dependency on libsass

### ISSUE THREAD

**Issue by ari** [saper/ports-exp#3]
Not sure if this can be fixed within the ports system, however the sassc pkg does not cause the libsass pkg to be upgraded from 1.0.1 to 3.3.3.

That is:
1. Build with poudriere
2. pkg upgrade textproc/sascc
3. -> libsass isn't automatically upgraded from the 1.0.1 I had previously installed

**Comment by saper** [comment]
Will check this. I am not currently requiring any version of libsass. This actually should be a pretty strict dependency.
